### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brandesign** [Sazonoff/UnitySaveSystem#1]
Hey,
your project looks very interesting and I would like to try it out for a project that is developed for our company internal use only. I can only do that with a licencing information though. Would you mind adding a license to the project?
Thanks!

**Comment by Sazonoff** [comment]
> Hey, your project looks very interesting and I would like to try it out for a project that is developed for our company internal use only. I can only do that with a licencing information though. Would you mind adding a license to the project? Thanks!

Hey, yeah, thanks for notifying. Added MIT license. Feel free to do whatever you want with the code 👍

**Comment by brandesign** [comment]
Great, thanks! :)
